name: Deploy snapshot to sonatype 

# Run workflow when the workflow to check the quality is completed
on:
  workflow_run:
    workflows: [CodeQL]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: |
            [
              {
                "id": "central",
                "name": "Maven Central",
                "url": "https://repo1.maven.org/maven2",
                "releases": {"enabled": "true"},
                "snapshots": {"enabled": "false"}
              },
              {
                "id": "sonatype_snapshots",
                "name": "Sonatype snapshots",
                "url": "https://s01.oss.sonatype.org/content/repositories/snapshots",
                "releases": {"enabled": "false"},
                "snapshots": {"enabled": "true"}
              }
            ]
          output_file: .m2/settings.xml

      - name: print settings.xml
        run: cat .m2/settings.xml

      - name: Release Maven package
        uses: WasiqB/maven-publish-action@v2.7.0
        with:
          settings_path: .m2/settings.xml
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          server_id: "sonatype_snapshots"
          server_username: ${{ secrets.nexus_username }}
          server_password: ${{ secrets.nexus_password }}
          maven_goals_phases: clean deploy -DaltDeploymentRepository=sonatype_snapshots::default::https://s01.oss.sonatype.org/content/repositories/snapshots